services:
  # سرویس بک‌اند
  - type: web
    name: freqtrade-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        value: 8000

  # سرویس فرانت‌اند
  - type: web
    name: freqtrade-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: freqtrade-backend
          envVarKey: RENDER_EXTERNAL_URL 